name: wallet-generator build
on: push
jobs:
  build:
    strategy:
      matrix:
        platform: [
          {os: ubuntu-latest, path: linux-x86_64},
          {os: macos-latest, path: darwin-x86_64},
          {os: windows-2019, path: windows-x86_64},
        ]
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.x
      - name: Checkout
        uses: actions/checkout@v1
      - name: Configure github for private modules
        shell: bash
        env:
          TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: git config --global url."https://error2215:${TOKEN}@github.com/core-coin/go-core".insteadOf "https://github.com/core-coin/go-core"
      - name: Build Mac and Linux
        if: matrix.platform.os == 'ubuntu-latest' || matrix.platform.os == 'macos-latest'
        run: |
          go build -o bin/wallet-generator main.go templates.go
      - name: Build Windows
        if: matrix.platform.os == 'windows-2019'
        shell: bash
        run: |
          go build -o bin/wallet-generator.exe main.go templates.go
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform.path }}
          path: ./bin
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Version
        id: version
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          release_name: ${{ steps.version.outputs.tag }} wallet-generator release
          draft: false
          prerelease: true
  artifacts:
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux-x86_64, windows-x86_64, darwin-x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.platform }}
          path: ./${{ matrix.platform }}
      - name: Zip
        run: zip ${{ matrix.platform }}.zip ${{ matrix.platform }}/* -j
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./${{ matrix.platform }}.zip
          asset_name: ${{ matrix.platform }}.zip
          asset_content_type: application/zip